export const NIVELES_ILUMINACION = [20, 50, 100, 200, 300, 500, 750, 1000, 2000];

export const TIPOS_ILUMINACION = {
  NATURAL: 'NATURAL',
  ARTIFICIAL: 'ARTIFICIAL', 
  COMBINADA: 'COMBINADA'
} as const;

export const PLANOS_TRABAJO = {
  HORIZONTAL: 'HORIZONTAL',
  VERTICAL: 'VERTICAL',
  OBLICUO: 'OBLICUO'
} as const;